### ISSUE TITLE
Resource Labs

### ISSUE THREAD

**Issue by gmspinheiro** [gmspinheiro/SEBC#4]

**Comment by rafaelarana** [comment]
Good. Some comments:
- We normally recommend to set yarn.scheduler.maximum-allocation-vcores to a lower value (5-6 instead of 10). Normally a Spark executor will reach contention on HDFS for so many cores although for a very cpu intensive could be necessary
- Also for mapreduce.map.memory.mb = 5120 and mapreduce.reduce.memory.mb = 5120 we recommend to be more conservative keeping the defaults (1G ) or doubling to 2 GB (sometimes 4 G for reducers) as users normally don't overwrite the defaults so for Hive queries it could be a waste of memory. Any free mem resource it's precious for big Spark Executors or just free memory for the OS cache.
